sudo: false
dist: trusty

language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

git:
  depth: 1

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpcs src -v --standard=PSR2 --exclude=Generic.Files.LineLength
  - vendor/bin/phpunit --coverage-text --colors
