name: Unit tests and checkstyle
on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
      - name: Run PHPCS
        run: ./vendor/bin/phpcs src -v --standard=PSR2 --exclude=Generic.Files.LineLength
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --coverage-text --colors
